name: flutter_app  # Replace with your app's name
description: A Flutter app to integrate with Flask API

publish_to: 'none'  # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"  # Update to your preferred Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  # For making HTTP requests
  image_picker: ^0.8.5+3  # For picking images from gallery or camera

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
